/**
 * What a Lousy Deal is, as a row.
 *
 * Contract §16 gives the field list and says the exact schema must be designed
 * against the installed Medusa rather than copied, so every choice below is
 * against 2.18.0's DML (`@medusajs/utils/dist/dml`), and §16's own rule —
 * "do not duplicate complete order/payment state into custom tables" — is why
 * this carries five facts about the purchase and not the purchase itself. The
 * order is Medusa's; this is what the certificate is made of.
 *
 * **The billing name is not here, and cannot be.** §5: billing identity is
 * order data and appears nowhere public. There is no column it could occupy,
 * which is the strongest form that rule can take.
 *
 * **`models/` is where this file has to live**, and that is not a style
 * choice. Medusa discovers a module's data models by scanning that one
 * directory — `importAllFromDir(resolve(normalizedPath, "models"))`,
 * `@medusajs/modules-sdk/dist/loaders/utils/load-internal.js:393` — and hands
 * what it finds to the migration generator. Defined anywhere else in the
 * module it still compiles, still registers with the service, and still makes
 * `medusa db:generate deal` answer `Skipped. No changes detected in your
 * models.` against an empty database, which is how this file came to be here.
 */

import { model } from "@medusajs/framework/utils";

/**
 * `hidden` is how §5's moderation requirement is met: an operator must be able
 * to hide a certificate "without a schema change, without a new serial, and
 * without reissuing". Soft-deleting the row is **not** that — Medusa's DML
 * scopes every unique index it generates with `deleted_at IS NULL`, so a
 * soft-deleted deal releases its `order_id` and a replayed webhook would mint
 * a second certificate for the same order. Hiding is a status; deleting is
 * deleting.
 */
export const DEAL_STATUSES = ["issued", "hidden"] as const;

export type DealStatus = (typeof DEAL_STATUSES)[number];

/**
 * The layout a deal issued today is issued under.
 *
 * **The storefront has its own copy of this number and that is correct.** It
 * is not shared state: the storefront must render an issued certificate by
 * dispatching on the `layout_version` the *row* carries, never by comparing it
 * to whatever the current constant happens to be. The two would only ever have
 * to agree if a renderer asked "is this the current layout?", which is the one
 * question §5 forbids it to ask.
 */
export const CURRENT_CERTIFICATE_LAYOUT = 1;

export const LousyDeal = model
  .define("lousy_deal", {
    id: model.id().primaryKey(),

    /** The Medusa order this was issued for. Unique, and that is the idempotency guarantee — see `../../subscribers`. */
    order_id: model.text(),

    /**
     * The sequential display number — `#18,421`.
     *
     * `model.autoincrement()` and not a counted `MAX(serial)+1`: two orders
     * completing at once read the same maximum and mint the same number, and
     * a serial's whole job is being believed. The DML maps this to a MikroORM
     * `Property({ autoincrement: true })`
     * (`@medusajs/utils/dist/dml/helpers/entity-builder/define-property.js:221-233`),
     * which Postgres backs with a real sequence.
     *
     * A sequence can leave gaps — a rolled-back insert consumes its number.
     * §5 forbids *inflating* the sequence to look busier, which is a different
     * thing; a skipped number understates volume rather than overstating it.
     */
    serial: model.autoincrement(),

    /**
     * The opaque address. §5: not the serial, not sequential, not guessable —
     * "a public URL nobody can enumerate is the entire reason it exists".
     * Generated by `./slug`, which is also where the alphabet is justified.
     */
    public_slug: model.text(),

    /** The tier's own title, as the order carried it. Copied, not referenced: a renamed product must not restyle an issued certificate. */
    tier: model.text(),

    /**
     * What was actually paid.
     *
     * `model.bigNumber()`, which materialises a second `raw_amount_paid` JSON
     * column alongside the numeric one, because that is how Medusa carries
     * money and decision `009`'s tax-inclusive pricing leaves a ~2.4e-21
     * residual on every tier that only `BigNumber`'s precision survives. A
     * float column would round it into the certificate's face value.
     */
    amount_paid: model.bigNumber(),
    currency_code: model.text(),

    /**
     * §5's two inscription fields, stored separately.
     *
     * Separately, and not as one string, because §5 requires an operator to be
     * able to "further sanitise, hide, or blank **either** field" later. One
     * column would make blanking the dedication a rewrite of the display name.
     *
     * Both nullable, and the empty pair is the common case: most buyers leave
     * both blank and the certificate has to look deliberate when they do.
     */
    display_name: model.text().nullable(),
    dedication: model.text().nullable(),

    /**
     * Frozen at issuance and never updated. §5: an issued certificate keeps
     * the layout it was issued under, so a redesign is additive and never
     * restyles a certificate somebody already owns. The row that renders from
     * this dispatches on it.
     */
    layout_version: model.number(),

    // Spread because `model.enum` takes `EnumLike | unknown[]` and refuses a
    // `readonly` tuple. `DEAL_STATUSES` stays `as const` so `DealStatus` is
    // the union rather than `string`; this copy is what the DML gets.
    status: model.enum([...DEAL_STATUSES]),

    /**
     * Distinct from the automatic `created_at`, which §16 does not name and
     * which is a row's history rather than a document's date. The certificate
     * states when the deal was made; that date must not move because a row was
     * ever rewritten.
     */
    issued_at: model.dateTime(),
  })
  .indexes([
    // All three unique, and each for its own reason. `order_id`: one order,
    // one certificate, enforced by the database rather than by a check the
    // subscriber runs before inserting. `public_slug`: an address that
    // resolves to two deals is not an address. `serial`: two certificates
    // claiming to be #4,102 is the failure the sequence exists to prevent, and
    // an index says so even though the sequence already makes it unreachable.
    { on: ["order_id"], unique: true },
    { on: ["public_slug"], unique: true },
    { on: ["serial"], unique: true },
  ]);
